server.address=0.0.0.0
server.port=8085
bind-address=0.0.0.0

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

##API
chatbot.api.url=https://api.openai.com/v1/chat/completions
chatbot.api.key=${WEBCHEF_OPENAI_API_KEY:}
chatbot.api.model=${CHATBOT_API_MODEL:gpt-4o-mini}

##FILE UPLOADF
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

file.community-upload-dir=uploads/community
file.course-upload-dir=uploads/course
file.course-video-dir=uploads/course/video
file.inquiry-upload-dir=uploads/inquiry
file.course-comment-upload-dir=uploads/course-comment

file.notice-upload-dir=uploads/notice

file.tips-upload-dir=uploads/tips


spring.config.import=optional:file:.env[.properties]

# Toss Payments
toss.client-key=test_ck_yL0qZ4G1VOYEB1YAmDno8oWb2MQY
toss.secret-key=test_sk_GjLJoQ1aVZa5ZPOgjkkd3w6KYe2R
toss.confirm-url=https://api.tosspayments.com/v1/payments/confirm
toss.cancel-url=https://api.tosspayments.com/v1/payments

